spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}

logging.level.org.springframework.batch: DEBUG
logging:
  level: INFO
---

spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:demo;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true