spring:
  config:
    activate:
      on-profile: local
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;
      username: sa
      password:
      driver-class-name: org.h2.Driver